name: CI

on: [push]

jobs:
  tests:
    name: Run Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build project
        run: yarn install
      - name: Run jests
        run: yarn test:ci
